/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package money;
public class Dollar extends Money{
  Dollar(int amount, String currency)
  {
    super(amount, currency);
  }
}
